# Generated by Django 2.0 on 2017-12-26 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200)),
                ('work_type', models.CharField(max_length=50)),
                ('bugid', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=50)),
                ('reopen', models.BooleanField()),
                ('reopen_reason', models.CharField(max_length=200)),
                ('solution', models.CharField(max_length=50)),
                ('solution_reason', models.CharField(max_length=200)),
                ('person', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('remake', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('permission', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Team')),
            ],
        ),
    ]
